#!/bin/bash
export DOMAIN=bancorenner.com.br
export CL_NAME=ocp-hml
export NODE_MASTER=master01-ocp3
export NODE_WORKER=worker01-ocp3,infra01-ocp3
export NODE_BOOTSTRAP=

# CLONE
export TEMPLATE=master-template
export DS=LAB_Local_Raid5
export NET="VM Network"
export FOLDER="OCP-HML"
export ESXI_HOST=192.168.100.101





export CL_DOMAIN="$CL_NAME.$DOMAIN"
export NODE_ALL="$NODE_MASTER,$NODE_WORKER,$NODE_BOOTSTRAP"
